### ISSUE TITLE
CI on Windows

### ISSUE THREAD

**Issue by webmozart** [puli/issues#115]
I enabled [AppVeyor](http://www.appveyor.com) on the [puli/repository](/puli/repository) repository. What we need now is an `appveyor.yml` that configures that tool correctly.

[Here's the reference](http://www.appveyor.com/docs/appveyor-yml), PR welcome. :) The PR can be used to test the configuration since AppVeyor should automatically run as soon as it detects a PR with an `appveyor.yml` file.

**Comment by stof** [comment]
See https://github.com/symfony/symfony/blob/2.3/appveyor.yml for an example config used in Symfony (the PHPUnit setup should be changed though as Symfony had to do some special things)

**Comment by aschempp** [comment]
We just recently added that to Contao CMS: https://github.com/contao/core-bundle/blob/master/appveyor.yml

Maybe @leofeyer can help?

**Comment by webmozart** [comment]
Help is greatly appreciated!

**Comment by leofeyer** [comment]
The [Contao appveyor.yml](https://github.com/contao/core-bundle/blob/master/appveyor.yml) file is pretty straightforward. It uses Chocolatey (`cinst`) to install OpenSSL and PHP and then loads Composer to install the dependencies.

The [Symfony appveyor.yml](https://github.com/symfony/symfony/blob/2.3/appveyor.yml) is a bit more complex, mainly because they handle the case that `C:\php` exists – which was never the case during my tests. Also, they are not using Chocolatey at all and download the PHP packages from windows.php.net instead. The rest is details :)

@webmozart I'd start with a simple file and built up from there depending on your needs.

**Comment by leofeyer** [comment]
Probably something like this:

```yml
build: false
shallow_clone: true
platform: x86
clone_folder: c:\projects\puli

install:
  - cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_bz2.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_exif.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_mysqli.dll >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_pdo_mysql.dll >> php.ini
  - echo extension=php_soap.dll >> php.ini
  - echo extension=php_sockets.dll >> php.ini
  - echo extension=php_xmlrpc.dll >> php.ini
  - echo extension=php_xsl.dll >> php.ini
  - SET PATH=c:\tools\php;%PATH%
  - cd c:\projects\puli
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-source --no-interaction

test_script:
  - cd c:\projects\puli
  - vendor\bin\phpunit.bat
```
