### ISSUE TITLE
Resource type

### ISSUE THREAD

**Issue by dantleech** [puli/issues#44]
It would be useful to be able to access the "type" for a given Resource payload.

For example, PHPCR Resource payload class is always of class type `PHPCR\NodeInterface`, but the "real" type of the node is determined by its PHPCR node-type.

So  I would expect something like:

````
$phpcrResource->getPayloadType(); // nt:article
$documentResource->getPayloadType(); // Fully\Qualified\Classname
````

The analogue of this can be seen in the Sling API under [getResourceType](http://sling.apache.org/apidocs/sling5/org/apache/sling/api/resource/Resource.html#getResourceMetadata()) - where a loose definition is given and basically the "resource resolver" is free to assign whatever it thinks is suitable (f.e. a JCR node type).

**Comment by webmozart** [comment]
Can you describe in a bit more detail what this type would be used for?

**Comment by dantleech** [comment]
My actual use case is that I am building  a REST API for a resource tree browser which supports drag-and-drop move operations.

It is necessary to describe which resources can accept other resources as children.

For example:

````
/
    articles/ [nt:article-folder]
        article-1/ [nt:article]
````

Nodes of type `nt:article-folder` only accept types of `[nt:article]`

So in the REST response it would be necessary to indicate this

````
{
   "articles": {
      # ...
     "_accepts": ["nt:article"]
}
````

But there is no programatic way to determine the "type" of the payload according to the scope/domain of the repository.

Also note that the above REST response isn't very good as there is no guarantee that `nt:article` won't conflict with a type from a different repository - I am addressing this with a "payload type registry" which maps aliases to a composite repository + type.

Don't know if that helps..

**Comment by webmozart** [comment]
Ok. And what is the payload of your resources?

**Comment by webmozart** [comment]
What about `NodeInterface` stored in the payload? Can the type be accessed via that interface?

**Comment by dantleech** [comment]
It can, but that would mean coupling to the PHPCR/ORM/xxx resource.

For example, to add the resource payload-type to each object in the REST response, I would need to first to explicitly check if it were a PHPCR resource, or an ODM resource and then determine the payload type accordingly.

**Comment by webmozart** [comment]
Is the resource tree browser supposed to work with any kind of resource or only specific ones? (e.g. would it work with core DirectoryResource and FileResource implementations?)

**Comment by dantleech** [comment]
Thats the plan. It would be great to have the ability to browse Twig templates on the filesystem for example.

**Comment by webmozart** [comment]
How would the resource type be set on those resources? After all your browser also needs to know that a DirectoryResource accepts children and a FileResource doesn't?

**Comment by dantleech** [comment]
Off the top of my head (I am still trying to puzzle this out):

````javascript
{
    'base_templates': {
        '_type': 'base_template_folder',
        '_accept': ['base_template', 'phpcr_template'],
        '_children': {
            'layout.html.twig': {
                'type': 'template',
                'body': '...'
                '_metadata': { ... }
            },
            ...
        }
    },
    'phpcr_templates': {
        '_type': 'phpcr_template_folder',
        '_accept': ['base_template', 'phpcr_template'],
        '_children': {
            'layout.html.twig': {
                'type': 'phpcr_template',
                'body': '...'
                '_metadata': { ... }
            },
            ...
        }
    },
}
````

So the resource aliases would be mapped:

````yaml
payload_alias_map:
    phpcr_template:
        - repository: doctrine_phpcr_odm # this is the Alias of the repository in the CmfResourceBundle
        - type: nt:file
    base_template:
        - repository: filesystem
        - type: ??
    phpcr_template_folder:
        ...
    base_template_folder:
        ...
````

And the "accept" would be mapped manually or inferred from metadata:

````yaml
rest_response_decorator:
    cmf_tree_browser_accept:
        base_template_folder: [ 'base_template', 'phpcr_template' ]
        phpcr_template_folder: [ 'base_template', 'phpcr_template' ]
````
